-- MySQL Script generated by MySQL Workbench
-- 01/13/16 00:04:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio` DEFAULT CHARACTER SET utf8 ;
USE `colegio` ;

-- -----------------------------------------------------
-- Table `colegio`.`facultad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio`.`facultad` ;

CREATE TABLE IF NOT EXISTS `colegio`.`facultad` (
  `COD_FACULTAD` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_FACULTAD` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_FACULTAD`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `colegio`.`carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio`.`carrera` ;

CREATE TABLE IF NOT EXISTS `colegio`.`carrera` (
  `COD_CARRERA` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CARRERA` VARCHAR(45) NULL DEFAULT NULL,
  `FACULTAD` INT(11) NOT NULL,
  PRIMARY KEY (`COD_CARRERA`),
  CONSTRAINT `fk_Carrera_Facultad`
    FOREIGN KEY (`FACULTAD`)
    REFERENCES `colegio`.`facultad` (`COD_FACULTAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Carrera_Facultad_idx` ON `colegio`.`carrera` (`FACULTAD` ASC);


-- -----------------------------------------------------
-- Table `colegio`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio`.`curso` ;

CREATE TABLE IF NOT EXISTS `colegio`.`curso` (
  `COD_CURSO` INT(11) NOT NULL AUTO_INCREMENT,
  `NOMBRE_CURSO` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`COD_CURSO`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table `colegio`.`curso_carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio`.`curso_carrera` ;

CREATE TABLE IF NOT EXISTS `colegio`.`curso_carrera` (
  `CURSO` INT(11) NOT NULL,
  `CARRERA` INT(11) NOT NULL,
  PRIMARY KEY (`CURSO`, `CARRERA`),
  CONSTRAINT `fk_Curso_has_Carrera_Carrera1`
    FOREIGN KEY (`CARRERA`)
    REFERENCES `colegio`.`carrera` (`COD_CARRERA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Carrera_Curso1`
    FOREIGN KEY (`CURSO`)
    REFERENCES `colegio`.`curso` (`COD_CURSO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Curso_has_Carrera_Carrera1_idx` ON `colegio`.`curso_carrera` (`CARRERA` ASC);

CREATE INDEX `fk_Curso_has_Carrera_Curso1_idx` ON `colegio`.`curso_carrera` (`CURSO` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
